name: My First Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, girhub actions!'

  pwd_ls_job:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
